### ISSUE TITLE
`npm run start`运行项目报错

### ISSUE THREAD

**Issue by Klay-Clam** [hql7/wl-micro-frontends#23]
**启动报错信息如下：**
```
warning ../../../../package.json: No license field
$ node config/start.js
即将进入所有模块并启动服务：["master","subapp-blog","subapp-ui"] ing...
master 开始启动... 全部启动需要时间，请稍加等候，或刷新浏览器即可
subapp-blog 开始启动... 全部启动需要时间，请稍加等候，或刷新浏览器即可
subapp-ui 开始启动... 全部启动需要时间，请稍加等候，或刷新浏览器即可
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Command failed: start http://localhost:6650/
  /bin/sh: start: command not found
  
      at ChildProcess.exithandler (child_process.js:303:12)
      at ChildProcess.emit (events.js:311:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:311:20)
      at Pipe.<anonymous> (net.js:668:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: 'start http://localhost:6650/',
    stdout: '',
    stderr: '/bin/sh: start: command not found\n'
  },
  child: ChildProcess {
    _events: [Object: null prototype] {
      close: [Function: exithandler],
      error: [Function: errorhandler]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 3,
    connected: false,
    signalCode: null,
    exitCode: 127,
    killed: false,
    spawnfile: '/bin/sh',
    _handle: null,
    spawnargs: [ '/bin/sh', '-c', 'start http://localhost:6650/' ],
    pid: 7365,
    stdin: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(asyncId)]: 24,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 25,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 26,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 34,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [ [Socket], [Socket], [Socket] ],
    [Symbol(kCapture)]: false
  }
} reason: Error: Command failed: start http://localhost:6650/
/bin/sh: start: command not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'start http://localhost:6650/',
  stdout: '',
  stderr: '/bin/sh: start: command not found\n'
}
```

**Comment by Klay-Clam** [comment]
https://github.com/hql7/wl-micro-frontends/issues/3
