### ISSUE TITLE
master启动不了

### ISSUE THREAD

**Issue by nihaoaWO** [hql7/wl-micro-frontends#46]
building 394/396 modules 2 active G:\\testVueCloud\\wl-micro-frontends-master\\subapp-blog\\node_modules\\_core-js@2.6.11@core-js\\library\\modules\\_to-length.js\n' } } reason: { RangeError [ERR_CHILD_PR
OCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:360:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd: 'npm run serve',
  stdout:
   '\n> subapp-blog@0.1.0 serve G:\\testVueCloud\\wl-micro-frontends-master\\subapp-blog\n> vue-cli-service serve\n\n INFO  Starting development server...\n',
  stderr:

**Comment by hql7** [comment]
一个一个启动



At 2020-08-04 12:05:40, "nihaoaWO" <notifications@github.com> wrote:

building 394/396 modules 2 active G:\testVueCloud\wl-micro-frontends-master\subapp-blog\node_modules\_core-js@2.6.11@core-js\library\modules\_to-length.js\n' } } reason: { RangeError [ERR_CHILD_PR
OCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
at Socket.onChildStderr (child_process.js:360:14)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:260:13)
at Socket.Readable.push (_stream_readable.js:219:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
cmd: 'npm run serve',
stdout:
'\n> subapp-blog@0.1.0 serve G:\testVueCloud\wl-micro-frontends-master\subapp-blog\n> vue-cli-service serve\n\n INFO Starting development server...\n',
stderr:

**Comment by nihaoaWO** [comment]
谢谢
